// Generated by Rcpp::compileAttributes() -- pxt kernel registration
#include <Rcpp.h>
Rcpp::NumericVector pxtCpp(Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector, double, int);
RcppExport SEXP _lifecontingencies_pxtCpp(SEXP x, SEXP t, SEXP lx, SEXP omega, SEXP method) {
BEGIN_RCPP
  return Rcpp::wrap(pxtCpp(Rcpp::as<Rcpp::NumericVector>(x), Rcpp::as<Rcpp::NumericVector>(t), Rcpp::as<Rcpp::NumericVector>(lx), Rcpp::as<double>(omega), Rcpp::as<int>(method)));
END_RCPP
}
