# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.mult3sum <- function(x, y, z) {
    .Call('lifecontingencies_mult3sum', PACKAGE = 'lifecontingencies', x, y, z)
}

.mult2sum <- function(x, y) {
    .Call('lifecontingencies_mult2sum', PACKAGE = 'lifecontingencies', x, y)
}

.fExnCpp <- function(T, y, n, i) {
    .Call('lifecontingencies_fExnCpp', PACKAGE = 'lifecontingencies', T, y, n, i)
}

.fAxnCpp <- function(T, y, n, i, m, k = 1) {
    .Call('lifecontingencies_fAxnCpp', PACKAGE = 'lifecontingencies', T, y, n, i, m, k)
}

.fIAxnCpp <- function(T, y, n, i, m, k = 1) {
    .Call('lifecontingencies_fIAxnCpp', PACKAGE = 'lifecontingencies', T, y, n, i, m, k)
}

.fDAxnCpp <- function(T, y, n, i, m, k = 1) {
    .Call('lifecontingencies_fDAxnCpp', PACKAGE = 'lifecontingencies', T, y, n, i, m, k)
}

.fAExnCpp <- function(T, y, n, i, k = 1) {
    .Call('lifecontingencies_fAExnCpp', PACKAGE = 'lifecontingencies', T, y, n, i, k)
}

